-- Share tokens are generated by the database (32 random bytes, base64url, 43 chars); users insert only scope + label.
alter table public.tracker_shares
  alter column token set default rtrim(translate(encode(extensions.gen_random_bytes(32), 'base64'), '+/', '-_'), '=');

revoke insert, delete on public.tracker_shares from authenticated;
grant insert (project_id, staff_ids, label) on public.tracker_shares to authenticated;

-- A revoked share is final: no un-revoke, no re-revoke, no label edits.
create function private.tracker_share_guard() returns trigger
language plpgsql security invoker set search_path = '' as $$
begin
  if old.revoked_at is not null then
    raise exception using errcode = 'P0001', message = 'share_revoked';
  end if;
  return new;
end $$;
revoke execute on function private.tracker_share_guard() from public, anon, authenticated;
create trigger tracker_share_guard before update on public.tracker_shares
  for each row execute function private.tracker_share_guard();
