-- tracker_v2 (plan .omc/plans/tracker-v2.md §3.1). Statement order is mandatory:
-- (0) extensions/schema/normaliser → (1) pre-asserts → (2) new tables → (3) nullable columns → (4) backfill
-- → (5) post-asserts → (6) NOT NULL/constraints/indexes/drops → (7) functions/triggers/RPCs → (8) RLS/grants → (9) publication

-- (0) ------------------------------------------------------------------------------------------------
create extension if not exists pg_cron;                        -- creates its own `cron` schema (Supabase docs)
create extension if not exists pg_net with schema extensions;
create schema if not exists private;                           -- not exposed by PostgREST; trigger functions only
revoke all on schema private from anon, authenticated, public;

create function public.tracker_normalize_cut(raw text) returns text
language sql immutable set search_path = '' as $$
  select regexp_replace(upper(regexp_replace(raw, '\s', '', 'g')), '^C0+(?=[0-9])', 'C')
$$;  -- TS mirror normalizeCutCode must match (fixture test)
revoke execute on function public.tracker_normalize_cut(text) from anon, public;
grant execute on function public.tracker_normalize_cut(text) to authenticated, service_role;

-- (1) pre-backfill asserts ----------------------------------------------------------------------------
do $$
begin
  if (select count(*) from public.tracker_projects) <> 1 then
    raise exception 'tracker_v2 pre-assert: expected exactly 1 project';
  end if;
  if (select count(*) from public.tracker_work_types) <> 3
     or (select count(*) from public.tracker_work_types where code in ('LO','GE','DO + SH') and archived_at is null) <> 3 then
    raise exception 'tracker_v2 pre-assert: expected work types LO, GE, DO + SH, none archived';
  end if;
  if exists (select 1 from public.tracker_tasks where project_id <> (select id from public.tracker_projects)) then
    raise exception 'tracker_v2 pre-assert: task outside the single project';
  end if;
  if exists (select 1 from public.tracker_tasks
             where length(public.tracker_normalize_cut(name)) not between 1 and 20) then
    raise exception 'tracker_v2 pre-assert: normalised task name length outside 1..20';
  end if;
  if exists (select 1 from public.tracker_tasks
             group by public.tracker_normalize_cut(name), work_type_id having count(*) > 1) then
    raise exception 'tracker_v2 pre-assert: two tasks share (cut, work type)';
  end if;
end $$;

-- (2) new tables (no rule triggers yet) -------------------------------------------------------------------
create table public.tracker_cuts (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.tracker_projects(id) on delete cascade,
  code text not null check (length(code) between 1 and 20 and code = public.tracker_normalize_cut(code)),
  budget bigint not null default 0 check (budget between 0 and 10000000000),        -- VND
  links jsonb not null default '[]' check (jsonb_typeof(links) = 'array' and jsonb_array_length(links) <= 20),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (project_id, code),
  unique (id, project_id)
);

create table public.tracker_strengths (
  id uuid primary key default gen_random_uuid(),
  label text not null unique check (length(trim(label)) between 1 and 40),
  all_rounder boolean not null default false,
  sort_order int not null default 0
);
create table public.tracker_staff_strengths (
  staff_id uuid not null references public.tracker_staff(id) on delete cascade,
  strength_id uuid not null references public.tracker_strengths(id) on delete cascade,
  primary key (staff_id, strength_id)
);
create index on public.tracker_staff_strengths (strength_id);

-- One row per submission (single entry, bulk batch or reversal); id = client operation id → retry-safe
create table public.tracker_adjustment_batches (
  id uuid primary key,                            -- generated by the client once per form submission
  project_id uuid not null references public.tracker_projects(id) on delete restrict,
  reason text not null check (length(trim(reason)) between 3 and 500),
  created_by text not null,                       -- stamped by trigger
  created_at timestamptz not null default now()
);
create index on public.tracker_adjustment_batches (project_id);

create table public.tracker_audit_log (
  id bigint generated always as identity primary key,
  at timestamptz not null default now(),
  actor text,                                     -- lower(jwt email); null for service role
  table_name text not null,
  row_id uuid not null,
  action text not null check (action in ('insert','update','delete')),
  old jsonb, new jsonb
);
create index on public.tracker_audit_log (table_name, row_id);

create table public.tracker_shares (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.tracker_projects(id) on delete cascade,
  token text not null unique check (token ~ '^[A-Za-z0-9_-]{43}$'),   -- randomBytes(32).base64url, server-side
  staff_ids uuid[] not null check (cardinality(staff_ids) between 1 and 50),
  label text check (label is null or length(label) <= 80),
  created_by text not null,                                            -- stamped by trigger
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);
create index on public.tracker_shares (project_id);

-- Assignment-notice outbox: at most one open debounce cycle per staff (digest)
create table public.tracker_notice_queue (
  staff_id uuid primary key references public.tracker_staff(id) on delete cascade,
  cycle_id uuid not null default gen_random_uuid(),   -- new per inserted row → never reused after delivery
  generation int not null default 1,                  -- bumps on every enqueue within the cycle
  task_ids uuid[] not null default '{}',              -- tasks whose assignment/dates changed in this cycle
  first_change_at timestamptz not null default now(),
  due_at timestamptz not null,                        -- last change + 10 min
  claimed_until timestamptz                           -- worker lease; reset to null by every enqueue
);

create table public.tracker_email_log (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('resources','schedule','assignment','reminder')),
  staff_id uuid references public.tracker_staff(id) on delete set null,
  to_email text not null,
  subject text not null,
  payload jsonb not null,                         -- {from, to, reply_to?, subject, html}: exactly what is (re)sent
  status text not null check (status in ('pending','accepted','failed')),
  idempotency_key text not null unique,           -- Resend Idempotency-Key; e.g. assign-{cycle_id}-{generation}
  resend_id text,
  error text,
  attempts int not null default 0,
  claim_token uuid,                               -- worker lease token
  claimed_until timestamptz,
  ref_date date,                                  -- reminders
  task_id uuid, cut_id uuid,                      -- context only (no FK: log outlives rows)
  created_by text,                                -- stamped by trigger; null for worker
  created_at timestamptz not null default now()
);
create index on public.tracker_email_log (created_at desc);
create index on public.tracker_email_log (staff_id);
create index on public.tracker_email_log (status, created_at) where status <> 'accepted';
create unique index tracker_email_reminder_once on public.tracker_email_log (staff_id, ref_date) where kind = 'reminder';

-- (3) nullable / defaulted columns -------------------------------------------------------------------------
alter table public.tracker_work_types
  add column project_id uuid references public.tracker_projects(id) on delete cascade,
  add column pay_pct numeric(5,2) not null default 0 check (pay_pct between 0 and 100),
  add column created_at timestamptz not null default now(),
  add column updated_at timestamptz not null default now();

alter table public.tracker_tasks
  add column cut_id uuid,
  add column version int not null default 1,
  add column links jsonb not null default '[]' check (jsonb_typeof(links) = 'array' and jsonb_array_length(links) <= 20);

alter table public.tracker_projects add column links jsonb not null default '[]'
  check (jsonb_typeof(links) = 'array' and jsonb_array_length(links) <= 20);

alter table public.tracker_staff add column email text
  check (email is null or (email = lower(email) and email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'));

-- (4) backfill -------------------------------------------------------------------------------------------
update public.tracker_work_types set
  project_id = (select id from public.tracker_projects),
  sort_order = case code when 'LO' then 10 when 'GE' then 20 when 'DO + SH' then 30 end,
  pay_pct    = case code when 'LO' then 30 when 'GE' then 30 when 'DO + SH' then 40 end;

insert into public.tracker_cuts (project_id, code)
select distinct project_id, public.tracker_normalize_cut(name) from public.tracker_tasks;

update public.tracker_tasks t set cut_id = c.id
from public.tracker_cuts c
where c.project_id = t.project_id and c.code = public.tracker_normalize_cut(t.name);

insert into public.tracker_strengths (label, all_rounder, sort_order) values
  ('LO', false, 1), ('Genga', false, 2), ('Douga + Shiage', false, 3), ('Sakkan', false, 4), ('Toàn năng', true, 5);

insert into public.tracker_staff_strengths (staff_id, strength_id)
select s.id, g.id
from public.tracker_staff s
cross join lateral regexp_split_to_table(s.strengths, '\s*,\s*') as v(val)
join public.tracker_strengths g on g.label = trim(v.val);

-- (5) post-backfill asserts -------------------------------------------------------------------------------
do $$
begin
  if exists (select 1 from public.tracker_tasks where cut_id is null) then
    raise exception 'tracker_v2 post-assert: task without cut';
  end if;
  if (select count(*) from public.tracker_tasks) <> 4 then
    raise exception 'tracker_v2 post-assert: task count changed';
  end if;
  if exists (select 1 from public.tracker_projects p
             where (select count(*) from public.tracker_work_types w where w.project_id = p.id) < 1
                or (select coalesce(sum(pay_pct), 0) from public.tracker_work_types w where w.project_id = p.id) <> 100) then
    raise exception 'tracker_v2 post-assert: project without types or pay_pct total <> 100';
  end if;
  if (select count(*) from public.tracker_staff_strengths) <> 26
     or (select count(*) from public.tracker_staff_strengths)
        <> (select count(*) from public.tracker_staff s
            cross join lateral regexp_split_to_table(s.strengths, '\s*,\s*') as v(val)
            where trim(v.val) <> '') then
    raise exception 'tracker_v2 post-assert: junction rows <> non-empty strength values (26)';
  end if;
end $$;

-- (6) NOT NULL / constraints / indexes / drops -------------------------------------------------------------
alter table public.tracker_work_types
  alter column project_id set not null,
  drop constraint tracker_work_types_code_key,
  drop column archived_at,
  add constraint tracker_work_types_project_code_key unique (project_id, code),
  add constraint tracker_work_types_id_project_key unique (id, project_id),
  add constraint tracker_work_types_project_order_key unique (project_id, sort_order) deferrable initially deferred;

alter table public.tracker_tasks
  alter column cut_id set not null,
  drop column name,
  drop constraint tracker_tasks_work_type_id_fkey,
  add constraint tracker_tasks_cut_fk  foreign key (cut_id, project_id) references public.tracker_cuts(id, project_id) on delete restrict,
  add constraint tracker_tasks_type_fk foreign key (work_type_id, project_id) references public.tracker_work_types(id, project_id) on delete restrict,
  add constraint tracker_tasks_cut_type_key unique (cut_id, work_type_id);
create index on public.tracker_tasks (cut_id, project_id);           -- covers tracker_tasks_cut_fk
create index on public.tracker_tasks (work_type_id, project_id);     -- covers tracker_tasks_type_fk
drop index public.tracker_tasks_work_type_id_idx;                    -- now redundant

create unique index tracker_staff_email_key on public.tracker_staff (email) where email is not null;
alter table public.tracker_staff drop column strengths;

-- Created here, not in (2): its FK needs tracker_work_types_id_project_key (added above).
create table public.tracker_pay_adjustments (
  id uuid primary key default gen_random_uuid(),
  batch_id uuid not null references public.tracker_adjustment_batches(id) on delete restrict,
  project_id uuid not null,
  cut_id uuid not null,
  work_type_id uuid not null,
  staff_id uuid not null references public.tracker_staff(id) on delete restrict,
  amount bigint not null check (amount <> 0 and abs(amount) <= 10000000000),   -- signed: bonus > 0, penalty < 0
  reason text not null check (length(trim(reason)) between 3 and 500),         -- row override or the batch reason
  reverses_id uuid unique references public.tracker_pay_adjustments(id) on delete restrict,
  created_by text not null,                       -- stamped by trigger
  created_at timestamptz not null default now(),
  foreign key (cut_id, project_id) references public.tracker_cuts(id, project_id) on delete restrict,
  foreign key (work_type_id, project_id) references public.tracker_work_types(id, project_id) on delete restrict
);
create index on public.tracker_pay_adjustments (cut_id, project_id);
create index on public.tracker_pay_adjustments (work_type_id, project_id);
create index on public.tracker_pay_adjustments (staff_id);
create index on public.tracker_pay_adjustments (batch_id);

-- (7) functions, triggers, RPCs ------------------------------------------------------------------------
-- Every rule trigger / RPC starts with the inline project lock:
--   perform pg_advisory_xact_lock(hashtextextended(<project_id>::text, 0));

-- 1. pipeline order rule (C1/C2): every insert and update
create function private.tracker_task_order() returns trigger
language plpgsql security invoker set search_path = '' as $$
declare
  v_order int;
  v_conflict uuid;
begin
  if tg_op = 'UPDATE' and new.project_id is distinct from old.project_id then
    raise exception using errcode = 'P0001', message = 'project_immutable';
  end if;
  perform pg_advisory_xact_lock(hashtextextended(new.project_id::text, 0));
  select sort_order into v_order from public.tracker_work_types where id = new.work_type_id;
  if v_order is null then
    return new;  -- unknown type: the FK reports it
  end if;
  select t.id into v_conflict
  from public.tracker_tasks t
  join public.tracker_work_types w on w.id = t.work_type_id
  where t.cut_id = new.cut_id and t.id <> new.id
    and ((w.sort_order < v_order and t.end_date >= new.start_date)
      or (w.sort_order > v_order and t.start_date <= new.end_date))
  order by w.sort_order
  limit 1;
  if v_conflict is not null then
    raise exception using errcode = 'P0001', message = 'order_conflict', detail = v_conflict::text;
  end if;
  return new;
end $$;
create trigger tracker_task_order before insert or update on public.tracker_tasks
  for each row execute function private.tracker_task_order();

-- 2. version bump (replaces t_upd on tasks) + updated_at on cuts / work types
create function private.tracker_bump_version() returns trigger
language plpgsql set search_path = '' as $$
begin
  new.version := old.version + 1;
  new.updated_at := now();
  return new;
end $$;
drop trigger t_upd on public.tracker_tasks;
create trigger tracker_bump_version before update on public.tracker_tasks
  for each row execute function private.tracker_bump_version();
create trigger t_upd before update on public.tracker_cuts       for each row execute function public.set_updated_at();
create trigger t_upd before update on public.tracker_work_types for each row execute function public.set_updated_at();

-- 3. work-type guard: project immutable; used types cannot be reordered or deleted
create function private.tracker_type_guard() returns trigger
language plpgsql security invoker set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    perform pg_advisory_xact_lock(hashtextextended(new.project_id::text, 0));
    return new;
  end if;
  perform pg_advisory_xact_lock(hashtextextended(old.project_id::text, 0));
  if tg_op = 'UPDATE' then
    if new.project_id is distinct from old.project_id then
      raise exception using errcode = 'P0001', message = 'project_immutable';
    end if;
    if old.sort_order is distinct from new.sort_order
       and exists (select 1 from public.tracker_tasks where work_type_id = old.id) then
      raise exception using errcode = 'P0001', message = 'type_in_use';
    end if;
    return new;
  end if;
  if exists (select 1 from public.tracker_tasks where work_type_id = old.id) then
    raise exception using errcode = 'P0001', message = 'type_in_use';
  end if;
  return old;
end $$;
create trigger tracker_type_guard before insert or update or delete on public.tracker_work_types
  for each row execute function private.tracker_type_guard();

-- 4. pay % total = 100 and >= 1 type, checked at commit
create function private.tracker_pct_total() returns trigger
language plpgsql security invoker set search_path = '' as $$
declare
  v_project uuid;
  v_count int;
  v_sum numeric;
begin
  if tg_table_name = 'tracker_projects' then
    v_project := new.id;
  elsif tg_op = 'DELETE' then
    v_project := old.project_id;
  else
    v_project := new.project_id;
  end if;
  perform pg_advisory_xact_lock(hashtextextended(v_project::text, 0));
  if not exists (select 1 from public.tracker_projects where id = v_project) then
    return null;
  end if;
  select count(*), coalesce(sum(pay_pct), 0) into v_count, v_sum
  from public.tracker_work_types where project_id = v_project;
  if v_count < 1 or v_sum <> 100 then
    raise exception using errcode = 'P0001', message = 'pct_total';
  end if;
  return null;
end $$;
create constraint trigger tracker_pct_total after insert or update or delete on public.tracker_work_types
  deferrable initially deferred for each row execute function private.tracker_pct_total();
create constraint trigger tracker_pct_total after insert on public.tracker_projects
  deferrable initially deferred for each row execute function private.tracker_pct_total();

-- 5. adjustments: actor stamp + reversal rules
create function private.tracker_adjustment_guard() returns trigger
language plpgsql security invoker set search_path = '' as $$
declare
  v_orig public.tracker_pay_adjustments;
begin
  perform pg_advisory_xact_lock(hashtextextended(new.project_id::text, 0));
  new.created_by := lower((select auth.jwt()) ->> 'email');
  if new.created_by is null then
    raise exception using errcode = 'P0001', message = 'adjustment_invalid';
  end if;
  if (select project_id from public.tracker_adjustment_batches where id = new.batch_id) is distinct from new.project_id then
    raise exception using errcode = 'P0001', message = 'adjustment_invalid';
  end if;
  if new.reverses_id is null then
    if not exists (select 1 from public.tracker_staff where id = new.staff_id and archived_at is null) then
      raise exception using errcode = 'P0001', message = 'adjustment_invalid';
    end if;
  else
    select * into v_orig from public.tracker_pay_adjustments where id = new.reverses_id;
    if not found
       or v_orig.reverses_id is not null
       or (v_orig.project_id, v_orig.cut_id, v_orig.work_type_id, v_orig.staff_id)
          is distinct from (new.project_id, new.cut_id, new.work_type_id, new.staff_id)
       or new.amount <> -v_orig.amount then
      raise exception using errcode = 'P0001', message = 'adjustment_invalid';
    end if;
  end if;
  return new;
end $$;
create trigger tracker_adjustment_guard before insert on public.tracker_pay_adjustments
  for each row execute function private.tracker_adjustment_guard();

-- 6. actor stamp
create function private.tracker_stamp_actor() returns trigger
language plpgsql security invoker set search_path = '' as $$
begin
  new.created_by := lower((select auth.jwt()) ->> 'email');
  return new;
end $$;
create trigger tracker_stamp_actor before insert on public.tracker_shares
  for each row execute function private.tracker_stamp_actor();
create trigger tracker_stamp_actor before insert on public.tracker_email_log
  for each row execute function private.tracker_stamp_actor();
create trigger tracker_stamp_actor before insert on public.tracker_adjustment_batches
  for each row execute function private.tracker_stamp_actor();

-- 7. audit (definer: writes the audit table users cannot write)
create function private.tracker_audit() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.tracker_audit_log (actor, table_name, row_id, action, old, new)
  values (
    lower((select auth.jwt()) ->> 'email'),
    tg_table_name,
    case when tg_op = 'DELETE' then old.id else new.id end,
    lower(tg_op),
    case when tg_op = 'INSERT' then null else to_jsonb(old) end,
    case when tg_op = 'DELETE' then null else to_jsonb(new) end
  );
  return null;
end $$;
create trigger tracker_audit_ins after insert on public.tracker_cuts
  for each row execute function private.tracker_audit();
create trigger tracker_audit_upd after update on public.tracker_cuts
  for each row when ((to_jsonb(old) - 'updated_at') is distinct from (to_jsonb(new) - 'updated_at'))
  execute function private.tracker_audit();
create trigger tracker_audit_del after delete on public.tracker_cuts
  for each row execute function private.tracker_audit();
create trigger tracker_audit_ins after insert on public.tracker_work_types
  for each row execute function private.tracker_audit();
create trigger tracker_audit_upd after update on public.tracker_work_types
  for each row when ((to_jsonb(old) - 'updated_at') is distinct from (to_jsonb(new) - 'updated_at'))
  execute function private.tracker_audit();
create trigger tracker_audit_del after delete on public.tracker_work_types
  for each row execute function private.tracker_audit();
create trigger tracker_audit_ins after insert on public.tracker_tasks
  for each row execute function private.tracker_audit();
create trigger tracker_audit_upd after update on public.tracker_tasks
  for each row when ((old.cut_id, old.work_type_id, old.staff_id, old.start_date, old.end_date, old.progress)
                     is distinct from (new.cut_id, new.work_type_id, new.staff_id, new.start_date, new.end_date, new.progress))
  execute function private.tracker_audit();
create trigger tracker_audit_del after delete on public.tracker_tasks
  for each row execute function private.tracker_audit();
create trigger tracker_audit_ins after insert on public.tracker_pay_adjustments
  for each row execute function private.tracker_audit();

-- 8. assignment-notice outbox (definer: users cannot write the queue)
create function private.tracker_enqueue_notice() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.tracker_notice_queue (staff_id, task_ids, due_at)
  values (new.staff_id, array[new.id], now() + interval '10 minutes')
  on conflict (staff_id) do update set
    due_at = excluded.due_at,
    generation = public.tracker_notice_queue.generation + 1,
    task_ids = (select array_agg(distinct x) from unnest(public.tracker_notice_queue.task_ids || new.id) x),
    claimed_until = null;
  return null;
end $$;
create trigger tracker_enqueue_notice_ins after insert on public.tracker_tasks
  for each row execute function private.tracker_enqueue_notice();
create trigger tracker_enqueue_notice_upd after update on public.tracker_tasks
  for each row when ((old.staff_id, old.start_date, old.end_date, old.cut_id, old.work_type_id)
                     is distinct from (new.staff_id, new.start_date, new.end_date, new.cut_id, new.work_type_id))
  execute function private.tracker_enqueue_notice();

revoke execute on all functions in schema private from public, anon, authenticated;

-- RPCs (SECURITY INVOKER; RLS applies) ----------------------------------------------------------------
create function public.tracker_create_project(p_name text, p_color text, p_types jsonb)
returns public.tracker_projects
language plpgsql security invoker set search_path = '' as $$
declare
  v_project public.tracker_projects;
begin
  insert into public.tracker_projects (name, color) values (p_name, p_color) returning * into v_project;
  perform pg_advisory_xact_lock(hashtextextended(v_project.id::text, 0));
  insert into public.tracker_work_types (project_id, code, label, color, pay_pct, sort_order)
  select v_project.id, e.code, e.label, e.color, e.pay_pct, e.sort_order
  from jsonb_to_recordset(p_types) as e(code text, label text, color text, pay_pct numeric, sort_order int);
  return v_project;
end $$;

create function public.tracker_save_work_types(p_project uuid, p_types jsonb)
returns setof public.tracker_work_types
language plpgsql security invoker set search_path = '' as $$
begin
  perform pg_advisory_xact_lock(hashtextextended(p_project::text, 0));
  delete from public.tracker_work_types w
  where w.project_id = p_project
    and not exists (select 1 from jsonb_array_elements(p_types) e where (e ->> 'id')::uuid = w.id);
  update public.tracker_work_types w set
    code = e.code, label = e.label, color = e.color, pay_pct = e.pay_pct, sort_order = e.sort_order
  from jsonb_to_recordset(p_types) as e(id uuid, code text, label text, color text, pay_pct numeric, sort_order int)
  where e.id is not null and w.id = e.id and w.project_id = p_project;
  insert into public.tracker_work_types (project_id, code, label, color, pay_pct, sort_order)
  select p_project, e.code, e.label, e.color, e.pay_pct, e.sort_order
  from jsonb_to_recordset(p_types) as e(id uuid, code text, label text, color text, pay_pct numeric, sort_order int)
  where e.id is null;
  return query select * from public.tracker_work_types where project_id = p_project order by sort_order;
end $$;

create function public.tracker_create_task(p_project uuid, p_staff uuid, p_type uuid, p_cut_code text,
                                           p_start date, p_end date, p_budget bigint default null)
returns jsonb
language plpgsql security invoker set search_path = '' as $$
declare
  v_code text := public.tracker_normalize_cut(p_cut_code);
  v_cut public.tracker_cuts;
  v_task public.tracker_tasks;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_project::text, 0));
  insert into public.tracker_cuts (project_id, code, budget)
  values (p_project, v_code, coalesce(p_budget, 0))
  on conflict (project_id, code) do nothing;
  select * into v_cut from public.tracker_cuts where project_id = p_project and code = v_code;
  insert into public.tracker_tasks (project_id, staff_id, work_type_id, cut_id, start_date, end_date)
  values (p_project, p_staff, p_type, v_cut.id, p_start, p_end)
  returning * into v_task;
  return jsonb_build_object('task', to_jsonb(v_task), 'cut', to_jsonb(v_cut));
end $$;

create function public.tracker_ensure_cut(p_project uuid, p_code text)
returns public.tracker_cuts
language plpgsql security invoker set search_path = '' as $$
declare
  v_code text := public.tracker_normalize_cut(p_code);
  v_cut public.tracker_cuts;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_project::text, 0));
  insert into public.tracker_cuts (project_id, code) values (p_project, v_code)
  on conflict (project_id, code) do nothing;
  select * into v_cut from public.tracker_cuts where project_id = p_project and code = v_code;
  return v_cut;
end $$;

create function public.tracker_add_adjustments(p_batch uuid, p_project uuid, p_reason text, p_entries jsonb)
returns setof public.tracker_pay_adjustments
language plpgsql security invoker set search_path = '' as $$
declare
  v_inserted int;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_project::text, 0));
  insert into public.tracker_adjustment_batches (id, project_id, reason)
  values (p_batch, p_project, p_reason)
  on conflict (id) do nothing;
  get diagnostics v_inserted = row_count;
  if v_inserted = 0 then
    return query select * from public.tracker_pay_adjustments where batch_id = p_batch order by created_at, id;
    return;
  end if;
  return query
  with ins as (
    insert into public.tracker_pay_adjustments
      (batch_id, project_id, cut_id, work_type_id, staff_id, amount, reason, reverses_id)
    select p_batch, p_project, e.cut_id, e.work_type_id, e.staff_id, e.amount,
           coalesce(e.reason, p_reason), e.reverses_id
    from jsonb_to_recordset(p_entries)
      as e(cut_id uuid, work_type_id uuid, staff_id uuid, amount bigint, reason text, reverses_id uuid)
    returning *
  )
  select * from ins;
end $$;

-- Claim RPCs (service role only; email worker)
create function public.tracker_claim_notices(p_limit int, p_lease interval)
returns setof public.tracker_notice_queue
language sql security invoker set search_path = '' as $$
  update public.tracker_notice_queue set claimed_until = now() + p_lease
  where staff_id in (
    select staff_id from public.tracker_notice_queue
    where due_at <= now() and (claimed_until is null or claimed_until < now())
    order by due_at
    for update skip locked
    limit p_limit)
  returning *;
$$;

create function public.tracker_claim_emails(p_limit int, p_lease interval)
returns setof public.tracker_email_log
language sql security invoker set search_path = '' as $$
  update public.tracker_email_log set
    claim_token = gen_random_uuid(), claimed_until = now() + p_lease, attempts = attempts + 1
  where id in (
    select id from public.tracker_email_log
    where status in ('pending','failed') and attempts < 5
      and created_at > now() - interval '23 hours'
      and (claimed_until is null or claimed_until < now())
    order by created_at
    for update skip locked
    limit p_limit)
  returning *;
$$;

revoke execute on function
  public.tracker_create_project(text, text, jsonb),
  public.tracker_save_work_types(uuid, jsonb),
  public.tracker_create_task(uuid, uuid, uuid, text, date, date, bigint),
  public.tracker_ensure_cut(uuid, text),
  public.tracker_add_adjustments(uuid, uuid, text, jsonb)
  from anon, public;
grant execute on function
  public.tracker_create_project(text, text, jsonb),
  public.tracker_save_work_types(uuid, jsonb),
  public.tracker_create_task(uuid, uuid, uuid, text, date, date, bigint),
  public.tracker_ensure_cut(uuid, text),
  public.tracker_add_adjustments(uuid, uuid, text, jsonb)
  to authenticated;
revoke execute on function
  public.tracker_claim_notices(int, interval),
  public.tracker_claim_emails(int, interval)
  from public, anon, authenticated;
grant execute on function
  public.tracker_claim_notices(int, interval),
  public.tracker_claim_emails(int, interval)
  to service_role;

-- (8) RLS + grants ---------------------------------------------------------------------------------------
alter table public.tracker_cuts               enable row level security;
alter table public.tracker_strengths          enable row level security;
alter table public.tracker_staff_strengths    enable row level security;
alter table public.tracker_shares             enable row level security;
alter table public.tracker_adjustment_batches enable row level security;
alter table public.tracker_pay_adjustments    enable row level security;
alter table public.tracker_audit_log          enable row level security;
alter table public.tracker_email_log          enable row level security;
alter table public.tracker_notice_queue       enable row level security;

revoke all on public.tracker_cuts, public.tracker_strengths, public.tracker_staff_strengths, public.tracker_shares,
  public.tracker_adjustment_batches, public.tracker_pay_adjustments, public.tracker_audit_log,
  public.tracker_email_log, public.tracker_notice_queue
  from anon, authenticated;

create policy cuts_rw            on public.tracker_cuts            for all to authenticated using ((select public.is_tracker_user())) with check ((select public.is_tracker_user()));
create policy strengths_rw       on public.tracker_strengths       for all to authenticated using ((select public.is_tracker_user())) with check ((select public.is_tracker_user()));
create policy staff_strengths_rw on public.tracker_staff_strengths for all to authenticated using ((select public.is_tracker_user())) with check ((select public.is_tracker_user()));
create policy shares_rw          on public.tracker_shares          for all to authenticated using ((select public.is_tracker_user())) with check ((select public.is_tracker_user()));
grant select, insert, update, delete on public.tracker_cuts, public.tracker_strengths,
  public.tracker_staff_strengths, public.tracker_shares to authenticated;

create policy batches_select     on public.tracker_adjustment_batches for select to authenticated using ((select public.is_tracker_user()));
create policy batches_insert     on public.tracker_adjustment_batches for insert to authenticated with check ((select public.is_tracker_user()));
create policy adjustments_select on public.tracker_pay_adjustments    for select to authenticated using ((select public.is_tracker_user()));
create policy adjustments_insert on public.tracker_pay_adjustments    for insert to authenticated with check ((select public.is_tracker_user()));
grant select, insert on public.tracker_adjustment_batches, public.tracker_pay_adjustments to authenticated;

create policy audit_select on public.tracker_audit_log for select to authenticated using ((select public.is_tracker_user()));
grant select on public.tracker_audit_log to authenticated;

create policy email_log_select on public.tracker_email_log for select to authenticated using ((select public.is_tracker_user()));
create policy email_log_insert on public.tracker_email_log for insert to authenticated with check ((select public.is_tracker_user()));
create policy email_log_update on public.tracker_email_log for update to authenticated using ((select public.is_tracker_user())) with check ((select public.is_tracker_user()));
grant select, insert on public.tracker_email_log to authenticated;
grant update (status, resend_id, error, attempts) on public.tracker_email_log to authenticated;

-- tracker_notice_queue: no policy, no grant (definer trigger + service role only)

-- (9) publication ---------------------------------------------------------------------------------------
alter publication supabase_realtime add table public.tracker_projects, public.tracker_staff, public.tracker_cuts,
  public.tracker_work_types, public.tracker_strengths, public.tracker_staff_strengths,
  public.tracker_pay_adjustments, public.tracker_shares;
